import DataCard from '../comp/BlockDataCard'
import Head from 'next/head'

export default function Home() {

  return (
    <div>
      
    <Head>
      <title>ConMon</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="main">
      <h1>Block Explorer</h1>
      <DataCard />
    </div>

    </div>
  );
}